### ISSUE TITLE
Add many-to-many relationships

### ISSUE THREAD

**Issue by emaxedon** [edadma/cras#1]
Need a way to add many-to-many relationships. Maybe using a keyword modifier like "array" on a property that points to a resource.

```
resource books
  authors authors array
```

**Comment by emaxedon** [comment]
A good example of how to implement many-to-many can be found here: http://stackoverflow.com/a/7296873.

**Comment by edadma** [comment]
GET and POST are working
the other request methods are next

**Comment by edadma** [comment]
PUT and PATCH are working if you don't include any many-to-many fields
to change a many-to-many use the special POST/DELETE routes that are added automatically
