### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by emaxedon** [edadma/cras#2]
Right now, requests to the server can't be made from a different origin. To enable cross-origin resource sharing, I imagine we'll need to set a header for that.

`Access-Control-Allow-Origin: http://example.com http://localhost:3000`

Maybe inside the 'reference.conf' file we can have a field where they can specify an array of allowed origins/domains under the 'server' block.

**Comment by edadma** [comment]
added `origin` key to `server` block in `reference.conf`
`Access-Control-Allow-Origin: *` header is included in response by default.
