### ISSUE TITLE
Handle OPTIONS request to handle Chrome preflight requests

### ISSUE THREAD

**Issue by emaxedon** [edadma/cras#3]
Should we have a resource at `/products`, and we want to make a POST via `window.fetch` inside a JavaScript file running on a Chrome browser, Chrome will send a preflight request using the OPTIONS method. This request cannot return `404` and must be handled.

Time to take a look at OPTIONS...

**Comment by edadma** [comment]
minimal generic support for OPTIONS method added

**Comment by emaxedon** [comment]
I think the OPTIONS preflight is still failing. Chrome returns the following error:

```Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.```

**Comment by edadma** [comment]
OPTIONS method now does not include `access-control-allow-origin` header in response
